-- Milo Supabase Database Schema
-- Zero Technical Debt. Strictly Typed. RLS Enforced.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Profiles Table
-- Stores user subscription status, mapped to their Auth UUID.
CREATE TABLE profiles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    subscription_status TEXT NOT NULL DEFAULT 'trial'
        CHECK (subscription_status IN ('trial', 'active', 'canceled', 'past_due', 'expired')),
    trial_end_date TIMESTAMPTZ,
    next_billing_date TIMESTAMPTZ,
    paddle_customer_id TEXT,
    paddle_subscription_id TEXT,
    paddle_last_event_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS) for Profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile"
    ON profiles FOR SELECT
    USING (auth.uid() = id);

-- Trigger to automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (id, email, trial_end_date)
    VALUES (new.id, new.email, NOW() + INTERVAL '14 days');
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. User Devices Table
-- Enforces the max 2 devices per account quota.
CREATE TABLE user_devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    device_hash TEXT NOT NULL CHECK (device_hash ~ '^[0-9a-f]{64}$'),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_active_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, device_hash) -- Prevent duplicate entries for the same device
);

-- RLS for Devices
ALTER TABLE user_devices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own devices"
    ON user_devices FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own devices (Deauthorize)"
    ON user_devices FOR DELETE
    USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.register_user_device(
    p_user_id UUID,
    p_device_hash TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_device_count INTEGER;
BEGIN
    IF p_device_hash IS NULL OR p_device_hash !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'Invalid device hash';
    END IF;

    PERFORM pg_advisory_xact_lock(hashtext(p_user_id::TEXT));

    UPDATE user_devices
    SET last_active_at = NOW()
    WHERE user_id = p_user_id AND device_hash = p_device_hash;

    IF FOUND THEN
        RETURN;
    END IF;

    SELECT COUNT(*)
    INTO v_device_count
    FROM user_devices
    WHERE user_id = p_user_id;

    IF v_device_count >= 2 THEN
        RAISE EXCEPTION 'Device quota reached';
    END IF;

    INSERT INTO user_devices (user_id, device_hash)
    VALUES (p_user_id, p_device_hash);
END;
$$;

REVOKE ALL ON FUNCTION public.register_user_device(UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.register_user_device(UUID, TEXT) TO service_role;

-- 3. Telemetry Signatures (The Cloud Blocklist)
-- Sourced from the reviewed monomacaw/milo-signatures manifest.
CREATE TABLE telemetry_signatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id TEXT NOT NULL UNIQUE CHECK (rule_id ~ '^[a-z0-9][a-z0-9._-]{2,127}$'),
    schema_version INTEGER NOT NULL DEFAULT 2 CHECK (schema_version = 2),
    signature_set_version TEXT NOT NULL CHECK (char_length(signature_set_version) BETWEEN 1 AND 128),
    vendor TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('bloat', 'intelligence')),
    display_name TEXT NOT NULL,
    process_name TEXT NOT NULL CHECK (char_length(process_name) BETWEEN 1 AND 160),
    launchd_label TEXT CHECK (launchd_label IS NULL OR launchd_label ~ '^[A-Za-z0-9._-]{1,256}$'),
    launchd_domain TEXT NOT NULL DEFAULT 'gui' CHECK (launchd_domain IN ('gui', 'system', 'both')),
    bundle_id TEXT CHECK (bundle_id IS NULL OR bundle_id ~ '^[A-Za-z0-9][A-Za-z0-9._-]{1,255}$'),
    executable_path_pattern TEXT CHECK (executable_path_pattern IS NULL OR char_length(executable_path_pattern) BETWEEN 1 AND 512),
    team_id TEXT CHECK (team_id IS NULL OR team_id ~ '^[A-Z0-9]{10}$'),
    signing_identifier TEXT CHECK (signing_identifier IS NULL OR signing_identifier ~ '^[A-Za-z0-9][A-Za-z0-9._-]{1,255}$'),
    min_macos TEXT CHECK (min_macos IS NULL OR min_macos ~ '^[0-9]{1,2}(\\.[0-9]{1,2}){0,2}$'),
    max_macos TEXT CHECK (max_macos IS NULL OR max_macos ~ '^[0-9]{1,2}(\\.[0-9]{1,2}){0,2}$'),
    termination_strategy TEXT NOT NULL CHECK (termination_strategy IN ('signal', 'launchctl_bootout', 'launchctl_disable', 'none')),
    severity SMALLINT NOT NULL DEFAULT 1 CHECK (severity BETWEEN 0 AND 3),
    verified BOOLEAN NOT NULL DEFAULT false,
    source_url TEXT,
    source_commit TEXT,
    deprecated_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    added_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(signature_set_version, rule_id),
    CHECK (team_id IS NOT NULL OR signing_identifier IS NOT NULL OR bundle_id IS NOT NULL)
);

-- RLS for Signatures (Public Read-Only)
ALTER TABLE telemetry_signatures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Signatures are public to read"
    ON telemetry_signatures FOR SELECT
    USING (true);

CREATE TABLE telemetry_signature_revocations (
    signature_set_version TEXT PRIMARY KEY,
    reason TEXT NOT NULL,
    revoked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE telemetry_signature_revocations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Signature revocations are public to read"
    ON telemetry_signature_revocations FOR SELECT
    USING (true);

-- Insert initial Apple Intelligence telemetry defaults. These are deliberately
-- multi-factor rules: process identity plus Apple signing identifier.
INSERT INTO telemetry_signatures (
    rule_id,
    schema_version,
    signature_set_version,
    vendor,
    category,
    display_name,
    process_name,
    launchd_label,
    launchd_domain,
    executable_path_pattern,
    signing_identifier,
    termination_strategy,
    severity,
    verified
) VALUES
    (
        'apple-intelligence-intelligenceplatformd-v2',
        2,
        'bootstrap-v2',
        'Apple',
        'intelligence',
        'intelligenceplatformd',
        'intelligenceplatformd',
        'com.apple.intelligenceplatformd',
        'both',
        '/System/Library/*/intelligenceplatformd',
        'com.apple.intelligenceplatformd',
        'launchctl_disable',
        2,
        true
    ),
    (
        'apple-intelligence-siriknowledged-v2',
        2,
        'bootstrap-v2',
        'Apple',
        'intelligence',
        'siriknowledged',
        'siriknowledged',
        'com.apple.siriknowledged',
        'gui',
        '/System/Library/*/siriknowledged',
        'com.apple.siriknowledged',
        'launchctl_disable',
        2,
        true
    ),
    (
        'apple-intelligence-siriinferenced-v2',
        2,
        'bootstrap-v2',
        'Apple',
        'intelligence',
        'siriinferenced',
        'siriinferenced',
        'com.apple.siriinferenced',
        'both',
        '/System/Library/*/siriinferenced',
        'com.apple.siriinferenced',
        'launchctl_disable',
        2,
        true
    ),
    (
        'apple-intelligence-intelligencecontextd-v2',
        2,
        'bootstrap-v2',
        'Apple',
        'intelligence',
        'intelligencecontextd',
        'intelligencecontextd',
        'com.apple.intelligencecontextd',
        'both',
        '/System/Library/*/intelligencecontextd',
        'com.apple.intelligencecontextd',
        'launchctl_disable',
        2,
        true
    )
ON CONFLICT (rule_id) DO UPDATE
SET signature_set_version = EXCLUDED.signature_set_version,
    vendor = EXCLUDED.vendor,
    category = EXCLUDED.category,
    display_name = EXCLUDED.display_name,
    process_name = EXCLUDED.process_name,
    launchd_label = EXCLUDED.launchd_label,
    launchd_domain = EXCLUDED.launchd_domain,
    executable_path_pattern = EXCLUDED.executable_path_pattern,
    signing_identifier = EXCLUDED.signing_identifier,
    termination_strategy = EXCLUDED.termination_strategy,
    severity = EXCLUDED.severity,
    verified = EXCLUDED.verified,
    updated_at = NOW();

-- 4. Paddle Webhook Idempotency
CREATE TABLE paddle_webhook_events (
    event_id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    occurred_at TIMESTAMPTZ,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE paddle_webhook_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.update_user_subscription(
    p_user_id UUID,
    p_status TEXT,
    p_customer_id TEXT,
    p_subscription_id TEXT,
    p_next_billing TIMESTAMPTZ,
    p_event_occurred_at TIMESTAMPTZ
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF p_status IS NULL OR p_status NOT IN ('active', 'trialing', 'past_due', 'paused', 'canceled') THEN
        RAISE EXCEPTION 'Invalid subscription status';
    END IF;

    UPDATE profiles
    SET subscription_status = CASE
            WHEN p_status IN ('active', 'trialing') THEN 'active'
            WHEN p_status = 'past_due' THEN 'past_due'
            ELSE 'canceled'
        END,
        paddle_customer_id = p_customer_id,
        paddle_subscription_id = p_subscription_id,
        next_billing_date = p_next_billing,
        paddle_last_event_at = COALESCE(p_event_occurred_at, NOW()),
        updated_at = NOW()
    WHERE id = p_user_id
        AND (
            p_event_occurred_at IS NULL
            OR paddle_last_event_at IS NULL
            OR p_event_occurred_at >= paddle_last_event_at
        );

    IF NOT FOUND THEN
        IF EXISTS (SELECT 1 FROM profiles WHERE id = p_user_id) THEN
            RETURN;
        END IF;
        RAISE EXCEPTION 'Profile not found';
    END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.update_user_subscription(UUID, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_subscription(UUID, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO service_role;

CREATE OR REPLACE FUNCTION public.cancel_user_subscription(
    p_user_id UUID,
    p_event_occurred_at TIMESTAMPTZ
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE profiles
    SET subscription_status = 'canceled',
        next_billing_date = NULL,
        paddle_last_event_at = COALESCE(p_event_occurred_at, NOW()),
        updated_at = NOW()
    WHERE id = p_user_id
        AND (
            p_event_occurred_at IS NULL
            OR paddle_last_event_at IS NULL
            OR p_event_occurred_at >= paddle_last_event_at
        );

    IF NOT FOUND THEN
        IF EXISTS (SELECT 1 FROM profiles WHERE id = p_user_id) THEN
            RETURN;
        END IF;
        RAISE EXCEPTION 'Profile not found';
    END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.cancel_user_subscription(UUID, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_user_subscription(UUID, TIMESTAMPTZ) TO service_role;
