import CryptoKit
import Foundation

struct EmbedHashes {
    let inputURL: URL
    let outputURL: URL

    func run() throws {
        let data = try Data(contentsOf: inputURL)
        var salt = Data(count: 32)
        let status = salt.withUnsafeMutableBytes { rawBuffer in
            guard let baseAddress = rawBuffer.baseAddress else { return errSecParam }
            return SecRandomCopyBytes(kSecRandomDefault, rawBuffer.count, baseAddress)
        }
        guard status == errSecSuccess else {
            throw EmbedHashesError.randomFailed(status)
        }

        let digest = SHA256.hash(data: salt + data).map { String(format: "%02x", $0) }.joined()
        let saltHex = salt.map { String(format: "%02x", $0) }.joined()
        let digestBytes = stride(from: 0, to: digest.count, by: 2).map { index -> String in
            let start = digest.index(digest.startIndex, offsetBy: index)
            let end = digest.index(start, offsetBy: 2)
            return "0x\(digest[start..<end])"
        }.joined(separator: ", ")
        let output: String
        if outputURL.pathExtension == "c" {
            output = """
            #include <stddef.h>

            const unsigned char mh_expected_executable_sha256[32] = { \(digestBytes) };
            const unsigned long mh_expected_executable_sha256_len = 32;
            const char mh_per_build_salt_hex[] = "\(saltHex)";
            """
        } else {
            output = """
            // Generated by Tools/embed-hashes.swift.
            public enum MiloEmbeddedHashes {
                public static let buildSaltHex = "\(saltHex)"
                public static let textDigestHex = "\(digest)"
            }
            """
        }
        try output.data(using: .utf8)?.write(to: outputURL, options: [.atomic])
    }
}

enum EmbedHashesError: Error {
    case usage
    case randomFailed(OSStatus)
}

do {
    guard CommandLine.arguments.count == 3 else {
        throw EmbedHashesError.usage
    }
    try EmbedHashes(
        inputURL: URL(fileURLWithPath: CommandLine.arguments[1]),
        outputURL: URL(fileURLWithPath: CommandLine.arguments[2])
    ).run()
} catch {
    FileHandle.standardError.write(Data("embed-hashes failed: \(error)\n".utf8))
    exit(1)
}
