#!/bin/bash
set -euo pipefail

if [[ "$#" -ne 1 ]]; then
    echo "Usage: $0 OUTPUT_XCCONFIG" >&2
    exit 64
fi

OUTPUT_PATH="$1"
CONFIGURATION_ENVIRONMENT="${MILO_CONFIGURATION_ENVIRONMENT:-}"
SERVICE_BASE_URL="${MILO_SERVICE_BASE_URL:-}"
LICENSE_PUBLIC_KEY="${MILO_LICENSE_PUBLIC_KEY:-}"
SPARKLE_PUBLIC_KEY="${SPARKLE_PUBLIC_ED_KEY:-}"

fail() {
    echo "Configuration generation failed: $1" >&2
    exit 78
}

validate_single_line() {
    local name="$1"
    local value="$2"
    if [[ "$value" == *$'\n'* || "$value" == *$'\r'* ]]; then
        fail "$name contains a line break"
    fi
}

validate_base64url_key() {
    local name="$1"
    local value="$2"
    if [[ ! "$value" =~ ^[A-Za-z0-9_-]{43}$ ]]; then
        fail "$name must be canonical unpadded base64url for exactly 32 bytes"
    fi
}

validate_sparkle_key() {
    local value="$1"
    if [[ ! "$value" =~ ^[A-Za-z0-9+/]{43}=$ ]]; then
        fail "SPARKLE_PUBLIC_ED_KEY must be canonical base64 for exactly 32 bytes"
    fi
}

validate_dns_host() {
    local host="$1"
    if [[ -z "$host" || "${#host}" -gt 253 ]]; then
        fail "MILO_SERVICE_BASE_URL host is invalid"
    fi
    local labels=()
    IFS='.' read -r -a labels <<< "$host"
    for label in "${labels[@]}"; do
        if [[ -z "$label" || "${#label}" -gt 63 || ! "$label" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$ ]]; then
            fail "MILO_SERVICE_BASE_URL host is invalid"
        fi
    done
}

case "$CONFIGURATION_ENVIRONMENT" in
    development)
        if [[ -z "$SERVICE_BASE_URL" ]]; then
            SERVICE_BASE_URL="https://milo-development.invalid"
        fi
        if [[ "$SERVICE_BASE_URL" == "https://gonggong.tech" || "$SERVICE_BASE_URL" == "https://gonggong.tech/" ]]; then
            fail "development configuration cannot use the production service"
        fi
        if [[ -z "$LICENSE_PUBLIC_KEY" ]]; then
            LICENSE_PUBLIC_KEY="A6EHv_POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg"
        fi
        ;;
    production)
        if [[ "$SERVICE_BASE_URL" != "https://gonggong.tech" ]]; then
            fail "production MILO_SERVICE_BASE_URL must be https://gonggong.tech"
        fi
        if [[ -z "$LICENSE_PUBLIC_KEY" ]]; then
            fail "production MILO_LICENSE_PUBLIC_KEY is required"
        fi
        if [[ -z "$SPARKLE_PUBLIC_KEY" ]]; then
            fail "production SPARKLE_PUBLIC_ED_KEY is required"
        fi
        ;;
    *)
        fail "MILO_CONFIGURATION_ENVIRONMENT must be development or production"
        ;;
esac

validate_single_line "MILO_SERVICE_BASE_URL" "$SERVICE_BASE_URL"
validate_single_line "MILO_LICENSE_PUBLIC_KEY" "$LICENSE_PUBLIC_KEY"
validate_single_line "SPARKLE_PUBLIC_ED_KEY" "$SPARKLE_PUBLIC_KEY"

if [[ ! "$SERVICE_BASE_URL" =~ ^https://[A-Za-z0-9.-]+$ ]]; then
    fail "MILO_SERVICE_BASE_URL must be an HTTPS origin without credentials, port, path, query, or fragment"
fi
validate_dns_host "${SERVICE_BASE_URL#https://}"
validate_base64url_key "MILO_LICENSE_PUBLIC_KEY" "$LICENSE_PUBLIC_KEY"
if [[ -n "$SPARKLE_PUBLIC_KEY" ]]; then
    validate_sparkle_key "$SPARKLE_PUBLIC_KEY"
fi

OUTPUT_DIRECTORY=$(dirname "$OUTPUT_PATH")
mkdir -p "$OUTPUT_DIRECTORY"
TEMP_PATH=$(mktemp "$OUTPUT_DIRECTORY/.milo-config.XXXXXX")
trap 'rm -f "$TEMP_PATH"' EXIT

SERVICE_HOST="${SERVICE_BASE_URL#https://}"
ESCAPED_SERVICE_BASE_URL="https:/\$()/$SERVICE_HOST"
{
    echo "// Generated by Tools/generate-build-configuration.sh; do not commit."
    echo "MILO_CONFIGURATION_ENVIRONMENT = $CONFIGURATION_ENVIRONMENT"
    echo "MILO_SERVICE_BASE_URL = $ESCAPED_SERVICE_BASE_URL"
    echo "MILO_LICENSE_PUBLIC_KEY = $LICENSE_PUBLIC_KEY"
    echo "SPARKLE_PUBLIC_ED_KEY = $SPARKLE_PUBLIC_KEY"
} > "$TEMP_PATH"

chmod 600 "$TEMP_PATH"
mv "$TEMP_PATH" "$OUTPUT_PATH"
trap - EXIT
echo "Generated validated $CONFIGURATION_ENVIRONMENT Pro configuration at $OUTPUT_PATH (values redacted)."
